### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [zuckschwerdt/asciidoc.tmbundle#7]
I would like to use your grammar for AsciiDoc but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by zuckschwerdt** [comment]
Thanks for your interest and your kind request. I'd say permissive is best here. At the end everything is just a remix. I'm going to license this under the terms of the "MIT License". Hope this helps, let me know if you release something -- I'd be happy to post a link.

**Comment by pchaigno** [comment]
> Hope this helps, let me know if you release something -- I'd be happy to post a link.

Sure. Thanks for the license and the quick answer!

**Comment by pchaigno** [comment]
@zuckschwerdt Your grammar is now used to highlight Asciidoc code on GitHub (files and code snippets in Markdown documents)! (See github/linguist#2119 for more information.)
